name: 'OpenTofu Plan and Apply'
description: 'Plan and apply OpenTofu modules with configurable inputs'
inputs:
  tofu_version:
    description: 'OpenTofu version to use'
    required: false
    default: 'latest'
  module_path:
    description: 'Path to the OpenTofu module'
    required: true
  backend_config:
    description: 'Backend configuration as multiline key=value pairs'
    required: false
  init_var_files:
    description: 'Init variable files as multiline paths'
    required: false
  init_vars:
    description: 'Init variables as multiline key=value pairs'
    required: false
  plan_var_files:
    description: 'Plan variable files as multiline paths'
    required: false
  plan_vars:
    description: 'Plan variables as multiline key=value pairs'
    required: false
  apply:
    description: 'Whether to apply the plan'
    required: false
    default: 'false'
  destroy:
    description: 'Whether to destroy infrastructure'
    required: false
    default: 'false'
  upload_plan:
    description: 'Upload plan file to GitHub artifacts'
    required: false
    default: 'true'
outputs:
  plan_file:
    description: 'Path to the generated plan file'
    value: ${{ steps.plan.outputs.plan_file }}
runs:
  using: 'composite'
  steps:
    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: ${{ inputs.tofu_version }}
    
    - name: Run OpenTofu
      id: plan
      shell: bash
      run: ${{ github.action_path }}/run.sh
      env:
        INPUT_MODULE_PATH: ${{ inputs.module_path }}
        INPUT_BACKEND_CONFIG: ${{ inputs.backend_config }}
        INPUT_INIT_VAR_FILES: ${{ inputs.init_var_files }}
        INPUT_INIT_VARS: ${{ inputs.init_vars }}
        INPUT_PLAN_VAR_FILES: ${{ inputs.plan_var_files }}
        INPUT_PLAN_VARS: ${{ inputs.plan_vars }}
        INPUT_APPLY: ${{ inputs.apply }}
        INPUT_DESTROY: ${{ inputs.destroy }}
        INPUT_UPLOAD_PLAN: ${{ inputs.upload_plan }}

    - name: Upload plan
      if: inputs.upload_plan == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: tofu-plan
        path: ${{ inputs.module_path }}/tfplan
