name: CI

on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Run tests
        run: ./test.sh
        
      - name: Test action
        uses: ./
        with:
          module_path: './test-module'
          apply: false
          upload_plan: false

  release:
    if: startsWith(github.ref, 'refs/tags/v') && github.ref_name == 'main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Update major version tag
        uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
